version: "3.6"

services:
  web:
    build: .
    command: gunicorn abhishek_portfolio.wsgi:application --bind 0.0.0.0:8000
    container_name: web
    volumes:
      - .:/usr/src/
    expose:
      - 8000
    env_file: .env
    depends_on:
      - db
  db:
    image: abhishekportfolio.azurecr.io/abhishekportfolio/postgres:13.1-alpine
    restart: always
    container_name: postgres
    volumes:
      - ./postgres_data:/home/runner/work/AbhishekPortfolio/AbhishekPortfolio/postgres_data
    env_file: .env-db
    expose: 
      - 5432
    ports:
      - 5432:5432
  nginx:
    image: abhishekportfolio.azurecr.io/abhishekportfolio/nginx:latest
    container_name: nginx
    build: ./nginx
    ports:
      - 8000:80
    depends_on:
      - web

volumes:
  postgres_data: