# Generated by Django 3.1.5 on 2021-01-16 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AchievementTags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'AchievementTags',
            },
        ),
        migrations.CreateModel(
            name='BlogTags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'BlogTags',
            },
        ),
        migrations.CreateModel(
            name='EducationList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=1, max_length=200)),
                ('institution', models.CharField(choices=[('UC', 'University of Canberra')], default='UC', max_length=10)),
                ('date_from', models.CharField(default=1, max_length=50)),
                ('date_to', models.CharField(default=1, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='JobList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=1, max_length=200)),
                ('company', models.CharField(default=1, max_length=200)),
                ('description', models.TextField(blank=True, max_length=1000)),
                ('date_from', models.CharField(default=1, max_length=50)),
                ('date_to', models.CharField(default=1, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectTags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'ProjectTags',
            },
        ),
        migrations.CreateModel(
            name='ProjectList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('short_description', models.TextField(max_length=100)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('upload', models.ImageField(blank=True, null=True, upload_to='frontend/static/frontend/img/uploads/')),
                ('slug', models.SlugField(blank=True, null=True)),
                ('tag', models.ManyToManyField(related_name='Project_List', to='backend.ProjectTags')),
            ],
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('short_description', models.TextField(max_length=100)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('upload', models.ImageField(blank=True, null=True, upload_to='frontend/static/frontend/img/uploads/')),
                ('slug', models.SlugField(blank=True, null=True)),
                ('tag', models.ManyToManyField(related_name='Project_List', to='backend.BlogTags')),
            ],
        ),
        migrations.CreateModel(
            name='AchievementList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('short_description', models.TextField(max_length=100)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('upload', models.ImageField(blank=True, null=True, upload_to='frontend/static/frontend/img/uploads/')),
                ('slug', models.SlugField(blank=True, null=True)),
                ('tag', models.ManyToManyField(related_name='AchievementTags', to='backend.AchievementTags')),
            ],
        ),
    ]
